### PR TITLE
Bump version for release

### PR DESCRIPTION
**Pull request by danielsdeleo**
The goal here is to make #51 and #53 available before the next ChefDK goes out.

### CODE REVIEW

**Comment by jaym** [comment]
:+1:

**Comment by reset** [comment]
@danielsdeleo if we're dropping testing on 1.9 we might also want to drop 1.9 support from the gemspec completely. If we do that, we should do a major version bump of this project

**Comment by danielsdeleo** [comment]
@reset I'll see if I can just add 1.9.3 back for now, it had nothing to do with the travis failures I was seeing, which turned out to be a bundler thing

**Comment by danielsdeleo** [comment]
@reset ok, I added 1.9.3 back for now, since I don't have a pressing need to nuke it. It appears I've hit some kind of travis rate limit, but I'm pretty sure it should pass once travis lets it through. Ok to ship this once travis is happy?

**Comment by reset** [comment]
@danielsdeleo absolutely!

gif-keyboard-9466766202220776232

**Comment by danielsdeleo** [comment]
Thanks, this is shipped to rubygems now

**Pull request merged**
